# Generated by Django 3.1.7 on 2021-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaAdderss',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, null=True, verbose_name='行政区')),
                ('pid', models.IntegerField(default=None, null=True, verbose_name='关联字段')),
            ],
            options={
                'verbose_name': '中国地址',
                'verbose_name_plural': '中国地址',
                'db_table': 'china',
            },
        ),
    ]
