# Generated by Django 3.1.7 on 2021-07-09 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbacimage', models.CharField(default=None, max_length=255, verbose_name='汽车展示背景图')),
                ('carmodel', models.CharField(default=None, max_length=255, verbose_name='汽车模型')),
                ('carprice', models.CharField(default=None, max_length=99, verbose_name='汽车价格')),
                ('carpower', models.CharField(default=None, max_length=255, verbose_name='汽车功率')),
                ('carspeeds', models.IntegerField(default=None, max_length=30, verbose_name='百公里加速耗时')),
                ('cartime', models.IntegerField(default=None, max_length=30, verbose_name='百公里')),
                ('carsign', models.IntegerField(default=None, max_length=100, verbose_name='标识')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'db_table': 'tb_carmessage',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carheader', models.CharField(default=None, max_length=255, verbose_name='汽车分类')),
                ('carinfo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car.carmodel', verbose_name='根据该id查询上一个表')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'db_table': 'tb_classification',
            },
        ),
    ]
