# Generated by Django 3.1.7 on 2021-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='carspeeds',
            field=models.IntegerField(default=None, verbose_name='百公里加速耗时'),
        ),
    ]
