# Generated by Django 3.1.7 on 2021-07-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210709_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLittleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('little', models.CharField(max_length=99, verbose_name='车型')),
            ],
            options={
                'verbose_name': '汽车型号',
                'verbose_name_plural': '汽车型号',
                'db_table': 'tb_littertype',
            },
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='carsign',
            field=models.IntegerField(default=None, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='cartime',
            field=models.IntegerField(default=None, verbose_name='百公里'),
        ),
    ]
