# Generated by Django 3.1.7 on 2021-07-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210709_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlittletype',
            name='sign',
            field=models.IntegerField(default=None, verbose_name='标识'),
        ),
    ]
