# Generated by Django 3.1.7 on 2021-07-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carlittletype_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartype',
            name='carinfo',
        ),
    ]
