# Generated by Django 3.1.7 on 2021-07-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_cartype_carsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodel', models.CharField(default=None, max_length=255, verbose_name='汽车模型')),
                ('carprice', models.CharField(default=None, max_length=99, verbose_name='汽车价格')),
                ('carpower', models.CharField(default=None, max_length=255, verbose_name='汽车功率')),
                ('carspeeds', models.IntegerField(default=None, verbose_name='百公里加速耗时')),
                ('cartime', models.IntegerField(default=None, verbose_name='百公里')),
                ('cartypesign', models.IntegerField(default=None, verbose_name='标识')),
            ],
            options={
                'verbose_name': '汽车型号',
                'verbose_name_plural': '汽车型号',
                'db_table': 'tb_detailCarModel',
            },
        ),
    ]
