# Generated by Django 3.1.7 on 2021-07-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_cardetailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetailmodel',
            name='carmodel',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='汽车模型'),
        ),
        migrations.AlterField(
            model_name='cardetailmodel',
            name='carpower',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='汽车功率'),
        ),
        migrations.AlterField(
            model_name='cardetailmodel',
            name='carprice',
            field=models.CharField(default=None, max_length=99, null=True, verbose_name='汽车价格'),
        ),
        migrations.AlterField(
            model_name='cardetailmodel',
            name='carspeeds',
            field=models.FloatField(default=None, null=True, verbose_name='百公里加速耗时'),
        ),
        migrations.AlterField(
            model_name='cardetailmodel',
            name='cartime',
            field=models.FloatField(default=None, null=True, verbose_name='百公里'),
        ),
        migrations.AlterField(
            model_name='cardetailmodel',
            name='cartypesign',
            field=models.FloatField(default=None, null=True, verbose_name='标识'),
        ),
    ]
