# Generated by Django 3.1.7 on 2021-07-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20210710_1259'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardetailmodel',
            table='tb_detailcarmodel',
        ),
    ]
