# Generated by Django 3.1.7 on 2021-07-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20210710_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetailmodel',
            name='carheader',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
