# Generated by Django 3.1.7 on 2021-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_cardetailmodel_carheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlittletype',
            name='detailsign',
            field=models.IntegerField(default=None),
        ),
    ]
