# Generated by Django 3.1.7 on 2021-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_carlittletype_detailsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailTechnicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicalsign', models.IntegerField(null=True, verbose_name='标识')),
                ('number_of_cylinders', models.IntegerField(null=True, verbose_name='气缸数')),
                ('displacement', models.CharField(max_length=255, null=True, verbose_name='排量')),
                ('bestpower', models.FloatField(null=True, verbose_name='最大功率')),
                ('maxtorque', models.IntegerField(null=True, verbose_name='最大扭矩')),
                ('maximumSpeed', models.IntegerField(null=True, verbose_name='最大扭矩对应发动机转速范围')),
                ('maxspeed', models.FloatField(null=True, verbose_name='最高时速')),
                ('zerohundertime', models.FloatField(null=True, verbose_name='0-100加速时间')),
                ('zerohuntersix', models.FloatField(null=True, verbose_name='0-160加速时间')),
                ('eightspped', models.FloatField(null=True, verbose_name='80-120km/h超车加速时间')),
                ('carlong', models.FloatField(null=True, verbose_name='长度')),
                ('carwidth', models.FloatField(null=True, verbose_name='宽度')),
                ('carwidthmirror', models.FloatField(null=True, verbose_name='宽度(带后视镜)')),
                ('carheight', models.FloatField(null=True, verbose_name='高度')),
                ('wheelbase', models.IntegerField(null=True, verbose_name='轴距')),
                ('weight', models.IntegerField(null=True, verbose_name='重量')),
                ('contentarea', models.IntegerField(null=True, verbose_name='行李厢容积(前)')),
                ('mostcontentarea', models.IntegerField(null=True, verbose_name='最大行李厢容积')),
                ('oilbox', models.IntegerField(null=True, verbose_name='燃油箱')),
                ('price', models.CharField(max_length=144, null=True, verbose_name='价格')),
            ],
            options={
                'verbose_name': '汽车详情数据',
                'verbose_name_plural': '汽车详情数据',
                'db_table': 'tb_alldata',
            },
        ),
    ]
