# Generated by Django 3.1.7 on 2021-07-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_cardetailtechnicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetailtechnicaldata',
            name='enginemostspeed',
            field=models.IntegerField(default=None, null=True, verbose_name='发动机最高转速'),
        ),
    ]
