# Generated by Django 3.1.7 on 2021-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_cardetailtechnicaldata_enginemostspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetailtechnicaldata',
            name='mostpowerspeed',
            field=models.IntegerField(default=None, null=True, verbose_name='最大功率对应最大转速'),
        ),
    ]
