# Generated by Django 3.1.7 on 2021-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_cardetailtechnicaldata_mostpowerspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetailtechnicaldata',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
