# Generated by Django 3.1.7 on 2021-07-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_cardetailtechnicaldata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesign', models.IntegerField(null=True, verbose_name='标志')),
                ('firsttitle', models.CharField(max_length=255, verbose_name='标题一')),
                ('firsttext', models.CharField(max_length=255, verbose_name='文本一')),
                ('videoone', models.CharField(max_length=255, verbose_name='视频一')),
                ('secondtitle', models.CharField(max_length=100, verbose_name='标题二')),
                ('secondtext', models.CharField(max_length=255, verbose_name='文本二')),
                ('videotwo', models.CharField(max_length=255, verbose_name='视频二')),
                ('thirddtitle', models.CharField(max_length=100, verbose_name='标题三')),
                ('thirdtext', models.CharField(max_length=255, verbose_name='文本三')),
                ('videothree', models.CharField(max_length=255, verbose_name='视频三')),
                ('fourdtitle', models.CharField(max_length=100, verbose_name='标题四')),
                ('fourtext', models.CharField(max_length=255, verbose_name='文本四')),
                ('videofour', models.CharField(max_length=255, verbose_name='视频四')),
            ],
            options={
                'verbose_name': '详情页基本信息',
                'verbose_name_plural': '详情页基本信息',
                'db_table': 'tb_te',
            },
        ),
    ]
