# Generated by Django 3.1.7 on 2021-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_temessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetailtechnicaldata',
            name='carimage',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='汽车图片'),
        ),
    ]
