# Generated by Django 3.1.7 on 2021-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
