# Generated by Django 3.1.7 on 2021-07-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210603_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdderssManger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adderssid', models.IntegerField(verbose_name='地址归属用户')),
                ('adderss', models.CharField(max_length=255, verbose_name='用户地址')),
            ],
            options={
                'verbose_name': '地址管理',
                'verbose_name_plural': '地址管理',
                'db_table': 'tb_adderss',
            },
        ),
    ]
