# Generated by Django 3.1.7 on 2021-07-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adderssmanger'),
    ]

    operations = [
        migrations.AddField(
            model_name='adderssmanger',
            name='adderssusername',
            field=models.CharField(default=None, max_length=255, verbose_name='用户姓名'),
        ),
        migrations.AddField(
            model_name='adderssmanger',
            name='if_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adderssmanger',
            name='phone',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='adderssmanger',
            name='adderss',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
